apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-scheduler
  template:
    metadata:
      labels:
        app: custom-scheduler
    spec:
      containers:
        - name: custom-cheduler-container
          image: custom-scheduler
          imagePullPolicy: Never
  strategy:
    # We only want one scheduler running at a time, or we will have
    # race conditions.
    type: Recreate
